// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

// Code generated by go generate; DO NOT EDIT.
package main

import (
	_ "enclave/extensions/tools/claude/go"
	_ "enclave/extensions/tools/codex/go"
	_ "enclave/extensions/tools/opencode/go"
)
