// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedLicenseHeader = `// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

`

func main() {
	out := flag.String("out", "tool_imports.go", "output file path")
	toolsDir := flag.String("tools", "", "extensions/tools directory (optional)")
	flag.Parse()

	wd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to resolve working dir: %v\n", err)
		os.Exit(1)
	}

	root := filepath.Clean(filepath.Join(wd, "..", ".."))
	toolsPath := *toolsDir
	if toolsPath == "" {
		toolsPath = filepath.Join(root, "extensions", "tools")
	}

	entries, err := os.ReadDir(toolsPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read tools dir: %v\n", err)
		os.Exit(1)
	}

	var imports []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		tool := entry.Name()
		goDir := filepath.Join(toolsPath, tool, "go")
		if !dirHasGoFiles(goDir) {
			continue
		}
		imports = append(imports, fmt.Sprintf("_ %q", filepath.ToSlash(filepath.Join("enclave", "extensions", "tools", tool, "go"))))
	}
	sort.Strings(imports)

	var builder strings.Builder
	builder.WriteString(generatedLicenseHeader)
	builder.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	builder.WriteString("package main\n\n")
	if len(imports) > 0 {
		builder.WriteString("import (\n")
		for _, imp := range imports {
			builder.WriteString("\t")
			builder.WriteString(imp)
			builder.WriteString("\n")
		}
		builder.WriteString(")\n")
	}

	source := []byte(builder.String())
	formatted, err := format.Source(source)
	if err != nil {
		formatted = source
	}

	outputPath := *out
	if !filepath.IsAbs(outputPath) {
		outputPath = filepath.Join(wd, outputPath)
	}

	// #nosec G306
	// Generated source files are intentionally repo-readable.
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write output file: %v\n", err)
		os.Exit(1)
	}
}

func dirHasGoFiles(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") {
			return true
		}
	}
	return false
}
