// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

package wslshim

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// goldenFile holds the command lines this package produces, so
// scripts/wsl-shim-verify.ps1 can feed the launcher's real output to a real
// wsl.exe instead of reimplementing the escaping in PowerShell.
const goldenFile = "testdata/wsl-quoting-golden.json"

// updateGoldenEnv regenerates the file instead of comparing against it.
const updateGoldenEnv = "ENCLAVE_UPDATE_GOLDEN"

type goldenCase struct {
	Name string `json:"name"`
	// Args is the argv the launcher is given and that must come back out.
	Args []string `json:"args"`
	// CommandLine is those arguments as the launcher escapes them, without
	// argv[0]: the verifier supplies its own wsl.exe invocation prefix.
	CommandLine string `json:"commandLine"`
}

type goldenTable struct {
	Comment string       `json:"comment"`
	Cases   []goldenCase `json:"cases"`
}

// multiArgGoldenCases cover argument lists rather than single arguments, which is
// where a separator bug would show up.
var multiArgGoldenCases = []struct {
	name string
	args []string
}{
	{"tool and value", []string{"--tool", "codex"}},
	{"passthrough after double dash", []string{"--tool", "claude", "--", "-p", `refactor the "auth" module\ into internal/auth`}},
	{"empty argument among others", []string{"exec", "", "--json"}},
	{"adjacent quoted arguments", []string{"a b", "c d"}},
	{"windows path argument", []string{"--mount", `C:\Users\p\data\`}},
	{"long argument", []string{strings.Repeat("a", 4096)}},
	// The launcher cannot avoid sending these two, and the probe carries a
	// backslash immediately before a quote on every single run, so they belong in
	// the set a real wsl.exe is checked against.
	{"probe script", []string{"-e", "/bin/sh", "-lc", probeScript}},
	{"cd fallback script", []string{
		"-e", "/bin/sh", "-c", cdScript, "enclave-wsl-launcher", "/home/p/my proj", "/usr/bin/enclave",
	}},
}

func buildGoldenTable(t *testing.T) goldenTable {
	t.Helper()

	table := goldenTable{
		Comment: "Generated by go test ./internal/wslshim with " + updateGoldenEnv + "=1. " +
			"Each commandLine is what the Windows launcher passes to CreateProcess for the " +
			"corresponding args; scripts/wsl-shim-verify.ps1 checks that a real wsl.exe hands " +
			"exactly those args to the Linux side.",
	}

	for _, tc := range goldenArgs {
		table.Cases = append(table.Cases, goldenCase{
			Name:        tc.name,
			Args:        []string{tc.arg},
			CommandLine: argumentsOf(t, []string{tc.arg}),
		})
	}
	for _, tc := range multiArgGoldenCases {
		table.Cases = append(table.Cases, goldenCase{
			Name:        tc.name,
			Args:        tc.args,
			CommandLine: argumentsOf(t, tc.args),
		})
	}
	return table
}

// argumentsOf renders the arguments portion of the command line by removing the
// argv[0] the launcher prepends, so the two stay guaranteed consistent.
func argumentsOf(t *testing.T, args []string) string {
	t.Helper()

	cmdLine, err := buildCommandLine(testExe, args)
	if err != nil {
		t.Fatalf("buildCommandLine(%q): %v", args, err)
	}
	return strings.TrimPrefix(cmdLine, escapeArg(testExe)+" ")
}

func TestQuotingGoldenFileMatchesImplementation(t *testing.T) {
	table := buildGoldenTable(t)

	encoded, err := json.MarshalIndent(table, "", "  ")
	if err != nil {
		t.Fatalf("marshal golden table: %v", err)
	}
	encoded = append(encoded, '\n')

	if os.Getenv(updateGoldenEnv) != "" {
		if err := os.MkdirAll(filepath.Dir(goldenFile), 0o750); err != nil {
			t.Fatalf("create testdata dir: %v", err)
		}
		// #nosec G306
		// Test fixtures are intentionally repo-readable.
		if err := os.WriteFile(goldenFile, encoded, 0o644); err != nil {
			t.Fatalf("write golden file: %v", err)
		}
		t.Logf("wrote %s", goldenFile)
		return
	}

	existing, err := os.ReadFile(goldenFile)
	if err != nil {
		t.Fatalf("read golden file (regenerate with %s=1): %v", updateGoldenEnv, err)
	}
	// Compare with line endings normalized: a Windows checkout with
	// core.autocrlf=true rewrites the file's newlines, which says nothing about
	// whether the content drifted.
	if normalizeNewlines(string(existing)) != normalizeNewlines(string(encoded)) {
		t.Errorf("%s is out of date. The manual wsl.exe verification in "+
			"scripts/wsl-shim-verify.ps1 reads it, so regenerate and commit it: "+
			"%s=1 go test ./internal/wslshim", goldenFile, updateGoldenEnv)
	}
}

func normalizeNewlines(s string) string {
	return strings.ReplaceAll(s, "\r\n", "\n")
}
