// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

//go:build !gen

// Code generated by scripts/gen_options.go; DO NOT EDIT.
package model

type OptionSources struct {
	GlobalOptionSources
	RunOptionSources
	AuthOptionSources
	BuildOptionSources
}

type GlobalOptionSources struct {
	Verbose OptionSource
}

type RunOptionSources struct {
	AddDirs          OptionSource
	AddReadonlyDirs  OptionSource
	AllowAllNetwork  OptionSource
	AllowDomains     OptionSource
	Backend          OptionSource
	BridgePorts      OptionSource
	Ephemeral        OptionSource
	HostConfig       OptionSource
	HostConfigPaths  OptionSource
	ImageInbox       OptionSource
	NetworkLog       OptionSource
	NoCache          OptionSource
	NoHistory        OptionSource
	NoMemory         OptionSource
	PlaywrightMCP    OptionSource
	Ports            OptionSource
	ProjectMount     OptionSource
	SessionMonitor   OptionSource
	SessionName      OptionSource
	Tool             OptionSource
	WorktreeMetadata OptionSource
	Yolo             OptionSource
}

type AuthOptionSources struct {
	AuthName     OptionSource
	AuthScope    OptionSource
	NoAPIKey     OptionSource
	PassAPIKey   OptionSource
	PassEnv      OptionSource
	ResetAuth    OptionSource
	SecretsScope OptionSource
}

type BuildOptionSources struct {
	BaseImage       OptionSource
	BuildGID        OptionSource
	BuildUID        OptionSource
	BuildxCacheDir  OptionSource
	BuildxCacheFrom OptionSource
	BuildxCacheTo   OptionSource
	CacheFrom       OptionSource
	Devcontainer    OptionSource
	Features        OptionSource
	ForceBaseImage  OptionSource
	ForceRebuild    OptionSource
	ImageName       OptionSource
	NoRebuild       OptionSource
	Progress        OptionSource
	RuntimeUIDRemap OptionSource
	Slim            OptionSource
	UseRemoteUser   OptionSource
}

func (s OptionSources) RunSources() RunOptionSources { return s.RunOptionSources }

func DefaultOptionSources() OptionSources {
	return OptionSources{
		GlobalOptionSources: GlobalOptionSources{
			Verbose: SourceDefault,
		},
		RunOptionSources: RunOptionSources{
			AddDirs:          SourceDefault,
			AddReadonlyDirs:  SourceDefault,
			AllowAllNetwork:  SourceDefault,
			AllowDomains:     SourceDefault,
			Backend:          SourceDefault,
			BridgePorts:      SourceDefault,
			Ephemeral:        SourceDefault,
			HostConfig:       SourceDefault,
			HostConfigPaths:  SourceDefault,
			ImageInbox:       SourceDefault,
			NetworkLog:       SourceDefault,
			NoCache:          SourceDefault,
			NoHistory:        SourceDefault,
			NoMemory:         SourceDefault,
			PlaywrightMCP:    SourceDefault,
			Ports:            SourceDefault,
			ProjectMount:     SourceDefault,
			SessionMonitor:   SourceDefault,
			SessionName:      SourceDefault,
			Tool:             SourceDefault,
			WorktreeMetadata: SourceDefault,
			Yolo:             SourceDefault,
		},
		AuthOptionSources: AuthOptionSources{
			AuthName:     SourceDefault,
			AuthScope:    SourceDefault,
			NoAPIKey:     SourceDefault,
			PassAPIKey:   SourceDefault,
			PassEnv:      SourceDefault,
			ResetAuth:    SourceDefault,
			SecretsScope: SourceDefault,
		},
		BuildOptionSources: BuildOptionSources{
			BaseImage:       SourceDefault,
			BuildGID:        SourceDefault,
			BuildUID:        SourceDefault,
			BuildxCacheDir:  SourceDefault,
			BuildxCacheFrom: SourceDefault,
			BuildxCacheTo:   SourceDefault,
			CacheFrom:       SourceDefault,
			Devcontainer:    SourceDefault,
			Features:        SourceDefault,
			ForceBaseImage:  SourceDefault,
			ForceRebuild:    SourceDefault,
			ImageName:       SourceDefault,
			NoRebuild:       SourceDefault,
			Progress:        SourceDefault,
			RuntimeUIDRemap: SourceDefault,
			Slim:            SourceDefault,
			UseRemoteUser:   SourceDefault,
		},
	}
}

func MergeOptionSources(base OptionSources, override OptionSources) OptionSources {
	if override.AddDirs != SourceUnset {
		base.AddDirs = override.AddDirs
	}
	if override.AddReadonlyDirs != SourceUnset {
		base.AddReadonlyDirs = override.AddReadonlyDirs
	}
	if override.AllowAllNetwork != SourceUnset {
		base.AllowAllNetwork = override.AllowAllNetwork
	}
	if override.AllowDomains != SourceUnset {
		base.AllowDomains = override.AllowDomains
	}
	if override.AuthName != SourceUnset {
		base.AuthName = override.AuthName
	}
	if override.AuthScope != SourceUnset {
		base.AuthScope = override.AuthScope
	}
	if override.Backend != SourceUnset {
		base.Backend = override.Backend
	}
	if override.BaseImage != SourceUnset {
		base.BaseImage = override.BaseImage
	}
	if override.BridgePorts != SourceUnset {
		base.BridgePorts = override.BridgePorts
	}
	if override.BuildGID != SourceUnset {
		base.BuildGID = override.BuildGID
	}
	if override.BuildUID != SourceUnset {
		base.BuildUID = override.BuildUID
	}
	if override.BuildxCacheDir != SourceUnset {
		base.BuildxCacheDir = override.BuildxCacheDir
	}
	if override.BuildxCacheFrom != SourceUnset {
		base.BuildxCacheFrom = override.BuildxCacheFrom
	}
	if override.BuildxCacheTo != SourceUnset {
		base.BuildxCacheTo = override.BuildxCacheTo
	}
	if override.CacheFrom != SourceUnset {
		base.CacheFrom = override.CacheFrom
	}
	if override.Devcontainer != SourceUnset {
		base.Devcontainer = override.Devcontainer
	}
	if override.Ephemeral != SourceUnset {
		base.Ephemeral = override.Ephemeral
	}
	if override.Features != SourceUnset {
		base.Features = override.Features
	}
	if override.ForceBaseImage != SourceUnset {
		base.ForceBaseImage = override.ForceBaseImage
	}
	if override.ForceRebuild != SourceUnset {
		base.ForceRebuild = override.ForceRebuild
	}
	if override.HostConfig != SourceUnset {
		base.HostConfig = override.HostConfig
	}
	if override.HostConfigPaths != SourceUnset {
		base.HostConfigPaths = override.HostConfigPaths
	}
	if override.ImageInbox != SourceUnset {
		base.ImageInbox = override.ImageInbox
	}
	if override.ImageName != SourceUnset {
		base.ImageName = override.ImageName
	}
	if override.NetworkLog != SourceUnset {
		base.NetworkLog = override.NetworkLog
	}
	if override.NoAPIKey != SourceUnset {
		base.NoAPIKey = override.NoAPIKey
	}
	if override.NoCache != SourceUnset {
		base.NoCache = override.NoCache
	}
	if override.NoHistory != SourceUnset {
		base.NoHistory = override.NoHistory
	}
	if override.NoMemory != SourceUnset {
		base.NoMemory = override.NoMemory
	}
	if override.NoRebuild != SourceUnset {
		base.NoRebuild = override.NoRebuild
	}
	if override.PassAPIKey != SourceUnset {
		base.PassAPIKey = override.PassAPIKey
	}
	if override.PassEnv != SourceUnset {
		base.PassEnv = override.PassEnv
	}
	if override.PlaywrightMCP != SourceUnset {
		base.PlaywrightMCP = override.PlaywrightMCP
	}
	if override.Ports != SourceUnset {
		base.Ports = override.Ports
	}
	if override.Progress != SourceUnset {
		base.Progress = override.Progress
	}
	if override.ProjectMount != SourceUnset {
		base.ProjectMount = override.ProjectMount
	}
	if override.ResetAuth != SourceUnset {
		base.ResetAuth = override.ResetAuth
	}
	if override.RuntimeUIDRemap != SourceUnset {
		base.RuntimeUIDRemap = override.RuntimeUIDRemap
	}
	if override.SecretsScope != SourceUnset {
		base.SecretsScope = override.SecretsScope
	}
	if override.SessionMonitor != SourceUnset {
		base.SessionMonitor = override.SessionMonitor
	}
	if override.SessionName != SourceUnset {
		base.SessionName = override.SessionName
	}
	if override.Slim != SourceUnset {
		base.Slim = override.Slim
	}
	if override.Tool != SourceUnset {
		base.Tool = override.Tool
	}
	if override.UseRemoteUser != SourceUnset {
		base.UseRemoteUser = override.UseRemoteUser
	}
	if override.Verbose != SourceUnset {
		base.Verbose = override.Verbose
	}
	if override.WorktreeMetadata != SourceUnset {
		base.WorktreeMetadata = override.WorktreeMetadata
	}
	if override.Yolo != SourceUnset {
		base.Yolo = override.Yolo
	}
	return base
}
