// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"

	"enclave/internal/config"
)

const generatedLicenseHeader = `// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

`

func main() {
	defs := config.OptionDefs()
	if err := writeOptionsRegistry(defs); err != nil {
		fail(err)
	}
	if err := writeOptionsCLI(defs); err != nil {
		fail(err)
	}
	if err := writeOptionSources(defs); err != nil {
		fail(err)
	}
}

func fail(err error) {
	_, _ = fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func writeOptionsRegistry(defs []config.OptionDef) error {
	var buf bytes.Buffer
	buf.WriteString(generatedLicenseHeader)
	buf.WriteString("//go:build !gen\n\n")
	buf.WriteString("// Code generated by scripts/gen_options.go; DO NOT EDIT.\n")
	buf.WriteString("package config\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"strings\"\n\n")
	buf.WriteString("\t\"enclave/internal/model\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("func OptionSpecs() []OptionSpec {\n")
	buf.WriteString("\tspecs := []OptionSpec{\n")
	for _, def := range defs {
		writeOptionSpec(&buf, def)
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\tattachCLIFlags(specs)\n")
	buf.WriteString("\treturn specs\n")
	buf.WriteString("}\n")
	return writeFormatted("internal/config/options_registry_gen.go", buf.Bytes())
}

func writeOptionSpec(buf *bytes.Buffer, def config.OptionDef) {
	fmt.Fprintf(buf, "\t\t{\n\t\t\tName: %q,\n", def.Name)
	fmt.Fprintf(buf, "\t\t\tGroup: %s,\n", optionGroupConst(def.Group))
	writeApplyDefaultsWithSource(buf, def)
	buf.WriteString("\t\t},\n")
}

func optionGroupConst(group config.OptionGroup) string {
	switch group {
	case config.OptionGroupGlobal:
		return "OptionGroupGlobal"
	case config.OptionGroupRun:
		return "OptionGroupRun"
	case config.OptionGroupAuth:
		return "OptionGroupAuth"
	case config.OptionGroupBuild:
		return "OptionGroupBuild"
	default:
		panic("unsupported option group: " + string(group))
	}
}

func writeApplyDefaultsWithSource(buf *bytes.Buffer, def config.OptionDef) {
	switch def.Apply {
	case config.ApplyNone:
		return
	case config.ApplyYoloDefault:
		buf.WriteString("\t\t\tApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {\n")
		buf.WriteString("\t\t\t\tif canOverride(sources.Yolo, source) && defaults.Yolo != nil {\n")
		buf.WriteString("\t\t\t\t\topts.ConfigDefaultYolo = defaults.Yolo\n")
		buf.WriteString("\t\t\t\t\tsources.Yolo = source\n")
		buf.WriteString("\t\t\t\t}\n")
		buf.WriteString("\t\t\t},\n")
	case config.ApplyBoolPtr:
		fmt.Fprintf(buf, "\t\t\tApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {\n\t\t\t\tif canOverride(sources.%s, source) && defaults.%s != nil {\n\t\t\t\t\topts.%s = *defaults.%s\n\t\t\t\t\tsources.%s = source\n\t\t\t\t}\n\t\t\t},\n", def.SourceField, def.DefaultsField, def.OptionField, def.DefaultsField, def.SourceField)
	case config.ApplyString:
		writeApplyStringWithSource(buf, def)
	case config.ApplySliceIfEmpty:
		fmt.Fprintf(buf, "\t\t\tApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {\n\t\t\t\tif canOverride(sources.%s, source) && len(defaults.%s) > 0 {\n\t\t\t\t\topts.%s = copyStringSlice(defaults.%s)\n\t\t\t\t\tsources.%s = source\n\t\t\t\t}\n\t\t\t},\n", def.SourceField, def.DefaultsField, def.OptionField, def.DefaultsField, def.SourceField)
	case config.ApplySliceMergeFeature:
		fmt.Fprintf(buf, "\t\t\tApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {\n\t\t\t\tif canOverride(sources.%s, source) && defaults.%s != nil {\n\t\t\t\t\topts.%s = mergeFeatureSlice(opts.%s, defaults.%s)\n\t\t\t\t\tsources.%s = source\n\t\t\t\t}\n\t\t\t},\n", def.SourceField, def.DefaultsField, def.OptionField, def.OptionField, def.DefaultsField, def.SourceField)
	case config.ApplySliceMergeHost:
		fmt.Fprintf(buf, "\t\t\tApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {\n\t\t\t\tif canOverride(sources.%s, source) && defaults.%s != nil {\n\t\t\t\t\topts.%s = mergeHostConfigSlice(opts.%s, defaults.%s)\n\t\t\t\t\tsources.%s = source\n\t\t\t\t}\n\t\t\t},\n", def.SourceField, def.DefaultsField, def.OptionField, def.OptionField, def.DefaultsField, def.SourceField)
	default:
		panic("unsupported apply kind: " + string(def.Apply))
	}
}

func writeApplyStringWithSource(buf *bytes.Buffer, def config.OptionDef) {
	defaultCheck := fmt.Sprintf("defaults.%s != \"\"", def.DefaultsField)
	assign := fmt.Sprintf("defaults.%s", def.DefaultsField)
	if def.TrimOnApply {
		defaultCheck = fmt.Sprintf("strings.TrimSpace(defaults.%s) != \"\"", def.DefaultsField)
		assign = fmt.Sprintf("strings.TrimSpace(defaults.%s)", def.DefaultsField)
	}
	fmt.Fprintf(buf, "\t\t\tApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {\n\t\t\t\tif canOverride(sources.%s, source) && %s {\n\t\t\t\t\topts.%s = %s\n\t\t\t\t\tsources.%s = source\n\t\t\t\t}\n\t\t\t},\n", def.SourceField, defaultCheck, def.OptionField, assign, def.SourceField)
}

func writeOptionsCLI(defs []config.OptionDef) error {
	var buf bytes.Buffer
	buf.WriteString(generatedLicenseHeader)
	buf.WriteString("//go:build !gen\n\n")
	buf.WriteString("// Code generated by scripts/gen_options.go; DO NOT EDIT.\n")
	buf.WriteString("package config\n\n")
	buf.WriteString("import \"enclave/internal/model\"\n\n")
	buf.WriteString("func optionCLIFlags() map[string][]CLIFlag {\n")
	buf.WriteString("\treturn map[string][]CLIFlag{\n")
	for _, def := range defs {
		if len(def.CLIFlags) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "\t\t%q: {\n", def.Name)
		for _, flag := range def.CLIFlags {
			writeCLIFlag(&buf, flag)
		}
		buf.WriteString("\t\t},\n")
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")
	return writeFormatted("internal/config/options_cli_gen.go", buf.Bytes())
}

func writeCLIFlag(buf *bytes.Buffer, flag config.CLIFlagDef) {
	open := "valueFlag"
	if flag.ValueKind == config.CLIValueNone {
		open = "boolFlag"
	}
	if flag.ValueKind == config.CLIValueNone {
		fmt.Fprintf(buf, "\t\t\t%s(%q, %q, func(opts *model.Options, sources *model.OptionSources) {\n", open, flag.Name, flag.Usage)
		writeCLIActionNoValue(buf, flag.Action)
		buf.WriteString("\t\t\t}),\n")
		return
	}

	fmt.Fprintf(buf, "\t\t\t%s(%q, %q, %q, func(opts *model.Options, sources *model.OptionSources, value string) error {\n", open, flag.Name, flag.Usage, flag.MissingValueMessage)
	writeCLIActionValue(buf, flag.Action)
	buf.WriteString("\t\t\t\treturn nil\n")
	buf.WriteString("\t\t\t}),\n")
}

func writeCLIActionNoValue(buf *bytes.Buffer, action config.CLIAction) {
	switch action.Kind {
	case config.CLIActionSetBool:
		fmt.Fprintf(buf, "\t\t\t\topts.%s = %t\n", action.OptionField, action.BoolValue)
		setSource(buf, action)
	case config.CLIActionSetBoolPtr:
		fmt.Fprintf(buf, "\t\t\t\tval := %t\n", action.BoolValue)
		fmt.Fprintf(buf, "\t\t\t\topts.%s = &val\n", action.OptionField)
		setSource(buf, action)
	case config.CLIActionCall:
		fmt.Fprintf(buf, "\t\t\t\t%s(opts, sources)\n", action.Call)
		setSource(buf, action)
	default:
		panic("unsupported CLI action for no-value flag: " + string(action.Kind))
	}
	if action.SetFlagField != "" {
		fmt.Fprintf(buf, "\t\t\t\topts.%s = true\n", action.SetFlagField)
	}
}

func writeCLIActionValue(buf *bytes.Buffer, action config.CLIAction) {
	switch action.Kind {
	case config.CLIActionSetString:
		fmt.Fprintf(buf, "\t\t\t\topts.%s = value\n", action.OptionField)
		setSource(buf, action)
		if action.SetFlagField != "" {
			fmt.Fprintf(buf, "\t\t\t\topts.%s = true\n", action.SetFlagField)
		}
	case config.CLIActionAppendString:
		fmt.Fprintf(buf, "\t\t\t\topts.%s = append(opts.%s, value)\n", action.OptionField, action.OptionField)
		setSource(buf, action)
	case config.CLIActionCall:
		fmt.Fprintf(buf, "\t\t\t\tif err := %s(opts, value); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n", action.Call)
		setSource(buf, action)
	default:
		panic("unsupported CLI action for value flag: " + string(action.Kind))
	}
}

func setSource(buf *bytes.Buffer, action config.CLIAction) {
	if action.SourceField == "" {
		return
	}
	fmt.Fprintf(buf, "\t\t\t\tsources.%s = model.SourceCLI\n", action.SourceField)
}

func writeOptionSources(defs []config.OptionDef) error {
	type group struct {
		Name   string
		Fields []string
	}
	groups := map[config.OptionGroup]*group{
		config.OptionGroupGlobal: {Name: "GlobalOptionSources"},
		config.OptionGroupRun:    {Name: "RunOptionSources"},
		config.OptionGroupAuth:   {Name: "AuthOptionSources"},
		config.OptionGroupBuild:  {Name: "BuildOptionSources"},
	}
	groupOrder := []config.OptionGroup{
		config.OptionGroupGlobal,
		config.OptionGroupRun,
		config.OptionGroupAuth,
		config.OptionGroupBuild,
	}
	for _, def := range defs {
		if def.SourceField == "" {
			continue
		}
		group := groups[def.Group]
		group.Fields = append(group.Fields, def.SourceField)
	}
	for _, grp := range groups {
		sort.Strings(grp.Fields)
	}

	var buf bytes.Buffer
	buf.WriteString(generatedLicenseHeader)
	buf.WriteString("//go:build !gen\n\n")
	buf.WriteString("// Code generated by scripts/gen_options.go; DO NOT EDIT.\n")
	buf.WriteString("package model\n\n")
	buf.WriteString("type OptionSources struct {\n")
	for _, grp := range groupOrder {
		fmt.Fprintf(&buf, "\t%s\n", groups[grp].Name)
	}
	buf.WriteString("}\n\n")
	for _, grp := range groupOrder {
		group := groups[grp]
		fmt.Fprintf(&buf, "type %s struct {\n", group.Name)
		for _, field := range group.Fields {
			fmt.Fprintf(&buf, "\t%s OptionSource\n", field)
		}
		buf.WriteString("}\n\n")
	}

	buf.WriteString("func (s OptionSources) RunSources() RunOptionSources { return s.RunOptionSources }\n\n")

	buf.WriteString("func DefaultOptionSources() OptionSources {\n")
	buf.WriteString("\treturn OptionSources{\n")
	for _, grp := range groupOrder {
		group := groups[grp]
		fmt.Fprintf(&buf, "\t\t%s: %s{\n", group.Name, group.Name)
		for _, field := range group.Fields {
			fmt.Fprintf(&buf, "\t\t\t%s: SourceDefault,\n", field)
		}
		buf.WriteString("\t\t},\n")
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	var allFields []string
	for _, grp := range groupOrder {
		allFields = append(allFields, groups[grp].Fields...)
	}
	sort.Strings(allFields)

	buf.WriteString("func MergeOptionSources(base OptionSources, override OptionSources) OptionSources {\n")
	for _, field := range allFields {
		fmt.Fprintf(&buf, "\tif override.%s != SourceUnset {\n\t\tbase.%s = override.%s\n\t}\n", field, field, field)
	}
	buf.WriteString("\treturn base\n}\n")

	return writeFormatted("internal/model/option_sources_gen.go", buf.Bytes())
}

func writeFormatted(path string, data []byte) error {
	formatted, err := format.Source(data)
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	rootDir, err := repoRoot()
	if err != nil {
		return err
	}
	fullPath := filepath.Join(rootDir, filepath.FromSlash(path))
	// #nosec G306
	// Generated source files are intentionally repo-readable.
	if err := os.WriteFile(fullPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func repoRoot() (string, error) {
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("locate generator file path")
	}
	scriptsDir := filepath.Dir(filename)
	return filepath.Dir(scriptsDir), nil
}
