# Copyright (C) 2026 EclipseSource GmbH and others.
#
# This program and the accompanying materials are made available under the
# terms of the MIT License, which is available in the project root.
#
# SPDX-License-Identifier: MIT

# npm / Node.js
server=/npmjs.org/8.8.8.8
server=/npmjs.com/8.8.8.8
server=/yarnpkg.com/8.8.8.8
server=/nodejs.org/8.8.8.8
