// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

//go:build !gen

// Code generated by scripts/gen_options.go; DO NOT EDIT.
package config

import (
	"strings"

	"enclave/internal/model"
)

func OptionSpecs() []OptionSpec {
	specs := []OptionSpec{
		{
			Name:  "tool",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Tool, source) && strings.TrimSpace(defaults.Tool) != "" {
					opts.Tool = strings.TrimSpace(defaults.Tool)
					sources.Tool = source
				}
			},
		},
		{
			Name:  "backend",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Backend, source) && strings.TrimSpace(defaults.Backend) != "" {
					opts.Backend = strings.TrimSpace(defaults.Backend)
					sources.Backend = source
				}
			},
		},
		{
			Name:  "host_config",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.HostConfig, source) && strings.TrimSpace(defaults.HostConfig) != "" {
					opts.HostConfig = strings.TrimSpace(defaults.HostConfig)
					sources.HostConfig = source
				}
			},
		},
		{
			Name:  "host_config_paths",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.HostConfigPaths, source) && defaults.HostConfigPaths != nil {
					opts.HostConfigPaths = mergeHostConfigSlice(opts.HostConfigPaths, defaults.HostConfigPaths)
					sources.HostConfigPaths = source
				}
			},
		},
		{
			Name:  "yolo",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Yolo, source) && defaults.Yolo != nil {
					opts.ConfigDefaultYolo = defaults.Yolo
					sources.Yolo = source
				}
			},
		},
		{
			Name:  "ephemeral",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Ephemeral, source) && defaults.Ephemeral != nil {
					opts.Ephemeral = *defaults.Ephemeral
					sources.Ephemeral = source
				}
			},
		},
		{
			Name:  "auth_scope",
			Group: OptionGroupAuth,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.AuthScope, source) && defaults.AuthScope != "" {
					opts.AuthScope = defaults.AuthScope
					sources.AuthScope = source
				}
			},
		},
		{
			Name:  "auth_name",
			Group: OptionGroupAuth,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.AuthName, source) && strings.TrimSpace(defaults.AuthName) != "" {
					opts.AuthName = strings.TrimSpace(defaults.AuthName)
					sources.AuthName = source
				}
			},
		},
		{
			Name:  "reset_auth",
			Group: OptionGroupAuth,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.ResetAuth, source) && defaults.ResetAuth != nil {
					opts.ResetAuth = *defaults.ResetAuth
					sources.ResetAuth = source
				}
			},
		},
		{
			Name:  "no_api_key",
			Group: OptionGroupAuth,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.NoAPIKey, source) && defaults.NoAPIKey != nil {
					opts.NoAPIKey = *defaults.NoAPIKey
					sources.NoAPIKey = source
				}
			},
		},
		{
			Name:  "pass_api_key",
			Group: OptionGroupAuth,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.PassAPIKey, source) && defaults.PassAPIKey != nil {
					opts.PassAPIKey = *defaults.PassAPIKey
					sources.PassAPIKey = source
				}
			},
		},
		{
			Name:  "secrets_scope",
			Group: OptionGroupAuth,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.SecretsScope, source) && defaults.SecretsScope != "" {
					opts.SecretsScope = defaults.SecretsScope
					sources.SecretsScope = source
				}
			},
		},
		{
			Name:  "pass_env",
			Group: OptionGroupAuth,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.PassEnv, source) && len(defaults.PassEnv) > 0 {
					opts.PassEnv = copyStringSlice(defaults.PassEnv)
					sources.PassEnv = source
				}
			},
		},
		{
			Name:  "allow_all_network",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.AllowAllNetwork, source) && defaults.AllowAllNetwork != nil {
					opts.AllowAllNetwork = *defaults.AllowAllNetwork
					sources.AllowAllNetwork = source
				}
			},
		},
		{
			Name:  "no_cache",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.NoCache, source) && defaults.NoCache != nil {
					opts.NoCache = *defaults.NoCache
					sources.NoCache = source
				}
			},
		},
		{
			Name:  "session_monitor",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.SessionMonitor, source) && defaults.SessionMonitor != nil {
					opts.SessionMonitor = *defaults.SessionMonitor
					sources.SessionMonitor = source
				}
			},
		},
		{
			Name:  "no_history",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.NoHistory, source) && defaults.NoHistory != nil {
					opts.NoHistory = *defaults.NoHistory
					sources.NoHistory = source
				}
			},
		},
		{
			Name:  "no_memory",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.NoMemory, source) && defaults.NoMemory != nil {
					opts.NoMemory = *defaults.NoMemory
					sources.NoMemory = source
				}
			},
		},
		{
			Name:  "image_inbox",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.ImageInbox, source) && defaults.ImageInbox != nil {
					opts.ImageInbox = *defaults.ImageInbox
					sources.ImageInbox = source
				}
			},
		},
		{
			Name:  "force_rebuild",
			Group: OptionGroupBuild,
		},
		{
			Name:  "no_rebuild",
			Group: OptionGroupBuild,
		},
		{
			Name:  "force_base_image",
			Group: OptionGroupBuild,
		},
		{
			Name:  "base_image",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.BaseImage, source) && strings.TrimSpace(defaults.BaseImage) != "" {
					opts.BaseImage = strings.TrimSpace(defaults.BaseImage)
					sources.BaseImage = source
				}
			},
		},
		{
			Name:  "devcontainer",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Devcontainer, source) && defaults.Devcontainer != nil {
					opts.Devcontainer = *defaults.Devcontainer
					sources.Devcontainer = source
				}
			},
		},
		{
			Name:  "use_remote_user",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.UseRemoteUser, source) && defaults.UseRemoteUser != nil {
					opts.UseRemoteUser = *defaults.UseRemoteUser
					sources.UseRemoteUser = source
				}
			},
		},
		{
			Name:  "slim",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Slim, source) && defaults.Slim != nil {
					opts.Slim = *defaults.Slim
					sources.Slim = source
				}
			},
		},
		{
			Name:  "image_name",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.ImageName, source) && strings.TrimSpace(defaults.ImageName) != "" {
					opts.ImageName = strings.TrimSpace(defaults.ImageName)
					sources.ImageName = source
				}
			},
		},
		{
			Name:  "features",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Features, source) && defaults.Features != nil {
					opts.Features = mergeFeatureSlice(opts.Features, defaults.Features)
					sources.Features = source
				}
			},
		},
		{
			Name:  "cache_from",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.CacheFrom, source) && len(defaults.CacheFrom) > 0 {
					opts.CacheFrom = copyStringSlice(defaults.CacheFrom)
					sources.CacheFrom = source
				}
			},
		},
		{
			Name:  "build_uid",
			Group: OptionGroupBuild,
		},
		{
			Name:  "build_gid",
			Group: OptionGroupBuild,
		},
		{
			Name:  "runtime_uid_remap",
			Group: OptionGroupBuild,
		},
		{
			Name:  "buildx_cache_dir",
			Group: OptionGroupBuild,
		},
		{
			Name:  "buildx_cache_from",
			Group: OptionGroupBuild,
		},
		{
			Name:  "buildx_cache_to",
			Group: OptionGroupBuild,
		},
		{
			Name:  "progress",
			Group: OptionGroupBuild,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Progress, source) && strings.TrimSpace(defaults.Progress) != "" {
					opts.Progress = strings.TrimSpace(defaults.Progress)
					sources.Progress = source
				}
			},
		},
		{
			Name:  "network_log",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.NetworkLog, source) && strings.TrimSpace(defaults.NetworkLog) != "" {
					opts.NetworkLog = strings.TrimSpace(defaults.NetworkLog)
					sources.NetworkLog = source
				}
			},
		},
		{
			Name:  "verbose",
			Group: OptionGroupGlobal,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Verbose, source) && defaults.Verbose != nil {
					opts.Verbose = *defaults.Verbose
					sources.Verbose = source
				}
			},
		},
		{
			Name:  "ports",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.Ports, source) && len(defaults.Ports) > 0 {
					opts.Ports = copyStringSlice(defaults.Ports)
					sources.Ports = source
				}
			},
		},
		{
			Name:  "session_name",
			Group: OptionGroupRun,
		},
		{
			Name:  "add_dirs",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.AddDirs, source) && len(defaults.AddDirs) > 0 {
					opts.AddDirs = copyStringSlice(defaults.AddDirs)
					sources.AddDirs = source
				}
			},
		},
		{
			Name:  "add_readonly_dirs",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.AddReadonlyDirs, source) && len(defaults.AddReadonlyDirs) > 0 {
					opts.AddReadonlyDirs = copyStringSlice(defaults.AddReadonlyDirs)
					sources.AddReadonlyDirs = source
				}
			},
		},
		{
			Name:  "project_mount",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.ProjectMount, source) && strings.TrimSpace(defaults.ProjectMount) != "" {
					opts.ProjectMount = strings.TrimSpace(defaults.ProjectMount)
					sources.ProjectMount = source
				}
			},
		},
		{
			Name:  "worktree_metadata",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.WorktreeMetadata, source) && strings.TrimSpace(defaults.WorktreeMetadata) != "" {
					opts.WorktreeMetadata = strings.TrimSpace(defaults.WorktreeMetadata)
					sources.WorktreeMetadata = source
				}
			},
		},
		{
			Name:  "allow_domains",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.AllowDomains, source) && len(defaults.AllowDomains) > 0 {
					opts.AllowDomains = copyStringSlice(defaults.AllowDomains)
					sources.AllowDomains = source
				}
			},
		},
		{
			Name:  "playwright_mcp",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.PlaywrightMCP, source) && defaults.PlaywrightMCP != nil {
					opts.PlaywrightMCP = *defaults.PlaywrightMCP
					sources.PlaywrightMCP = source
				}
			},
		},
		{
			Name:  "bridge_ports",
			Group: OptionGroupRun,
			ApplyDefaultsWithSource: func(opts *model.Options, defaults Defaults, source model.OptionSource, sources *model.OptionSources) {
				if canOverride(sources.BridgePorts, source) && len(defaults.BridgePorts) > 0 {
					opts.BridgePorts = copyStringSlice(defaults.BridgePorts)
					sources.BridgePorts = source
				}
			},
		},
		{
			Name:  "theia_api_port",
			Group: OptionGroupRun,
		},
		{
			Name:  "theia_api_token",
			Group: OptionGroupRun,
		},
	}
	attachCLIFlags(specs)
	return specs
}
