// Copyright (C) 2026 EclipseSource GmbH and others.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.
//
// SPDX-License-Identifier: MIT

//go:build !gen

// Code generated by scripts/gen_options.go; DO NOT EDIT.
package config

import "enclave/internal/model"

func optionCLIFlags() map[string][]CLIFlag {
	return map[string][]CLIFlag{
		"tool": {
			valueFlag("--tool", "Tool profile (default: claude)", "--tool requires a value (see --help for available tools)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.Tool = value
				sources.Tool = model.SourceCLI
				return nil
			}),
		},
		"backend": {
			valueFlag("--backend", "Isolation backend: docker|qemu (default: docker)", "--backend requires a value (docker|qemu)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.Backend = value
				sources.Backend = model.SourceCLI
				return nil
			}),
		},
		"host_config": {
			valueFlag("--host-config", "Host config reuse: none|passthrough", "--host-config requires a value (none|passthrough)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyHostConfig(opts, value); err != nil {
					return err
				}
				sources.HostConfig = model.SourceCLI
				return nil
			}),
		},
		"yolo": {
			boolFlag("--yolo", "Enable YOLO mode", func(opts *model.Options, sources *model.OptionSources) {
				val := true
				opts.YoloOverride = &val
				sources.Yolo = model.SourceCLI
			}),
			boolFlag("--no-yolo", "Disable YOLO mode", func(opts *model.Options, sources *model.OptionSources) {
				val := false
				opts.YoloOverride = &val
				sources.Yolo = model.SourceCLI
			}),
		},
		"ephemeral": {
			boolFlag("--ephemeral", "Ephemeral session (no auth or env stores)", func(opts *model.Options, sources *model.OptionSources) {
				opts.Ephemeral = true
				sources.Ephemeral = model.SourceCLI
			}),
		},
		"auth_scope": {
			valueFlag("--auth-scope", "Auth scope: shared|project", "--auth-scope requires a value (shared|project)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyAuthScope(opts, value); err != nil {
					return err
				}
				sources.AuthScope = model.SourceCLI
				return nil
			}),
		},
		"auth_name": {
			valueFlag("--auth-name", "Named auth identity: select a separate shared auth store per tool", "--auth-name requires a value (e.g. personal, api)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyAuthName(opts, value); err != nil {
					return err
				}
				sources.AuthName = model.SourceCLI
				return nil
			}),
		},
		"reset_auth": {
			boolFlag("--reset-auth", "Clear stored auth files and persisted API keys", func(opts *model.Options, sources *model.OptionSources) {
				opts.ResetAuth = true
				sources.ResetAuth = model.SourceCLI
			}),
		},
		"no_api_key": {
			boolFlag("--no-api-key", "Disable API key injection", func(opts *model.Options, sources *model.OptionSources) {
				opts.NoAPIKey = true
				sources.NoAPIKey = model.SourceCLI
			}),
		},
		"pass_api_key": {
			boolFlag("--pass-api-key", "Allow API key injection in --ephemeral mode", func(opts *model.Options, sources *model.OptionSources) {
				opts.PassAPIKey = true
				sources.PassAPIKey = model.SourceCLI
			}),
		},
		"secrets_scope": {
			valueFlag("--secrets-scope", "Secrets scope: project|global|both", "--secrets-scope requires a value (project|global|both)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applySecretsScope(opts, value); err != nil {
					return err
				}
				sources.SecretsScope = model.SourceCLI
				return nil
			}),
		},
		"pass_env": {
			valueFlag("--pass-env", "Env vars to pass into the container (comma-separated)", "--pass-env requires a value", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyPassEnv(opts, value); err != nil {
					return err
				}
				sources.PassEnv = model.SourceCLI
				return nil
			}),
		},
		"allow_all_network": {
			boolFlag("--allow-all-network", "Disable network restrictions", func(opts *model.Options, sources *model.OptionSources) {
				opts.AllowAllNetwork = true
				sources.AllowAllNetwork = model.SourceCLI
			}),
		},
		"no_cache": {
			boolFlag("--no-cache", "Disable package caches", func(opts *model.Options, sources *model.OptionSources) {
				opts.NoCache = true
				sources.NoCache = model.SourceCLI
			}),
		},
		"session_monitor": {
			boolFlag("--session-monitor", "Run the agent under the managed tmux session (enables status snapshots)", func(opts *model.Options, sources *model.OptionSources) {
				opts.SessionMonitor = true
				sources.SessionMonitor = model.SourceCLI
			}),
		},
		"no_history": {
			boolFlag("--no-history", "Disable shell history", func(opts *model.Options, sources *model.OptionSources) {
				opts.NoHistory = true
				sources.NoHistory = model.SourceCLI
			}),
		},
		"no_memory": {
			boolFlag("--no-memory", "Disable per-project agent memory", func(opts *model.Options, sources *model.OptionSources) {
				opts.NoMemory = true
				sources.NoMemory = model.SourceCLI
			}),
		},
		"image_inbox": {
			boolFlag("--image-inbox", "Mount a read-only host image inbox at /mnt/host-images", func(opts *model.Options, sources *model.OptionSources) {
				opts.ImageInbox = true
				sources.ImageInbox = model.SourceCLI
			}),
		},
		"force_rebuild": {
			boolFlag("--rebuild", "Force image rebuild", func(opts *model.Options, sources *model.OptionSources) {
				opts.ForceRebuild = true
				sources.ForceRebuild = model.SourceCLI
			}),
		},
		"no_rebuild": {
			boolFlag("--no-rebuild", "Use existing images and suppress all image builds", func(opts *model.Options, sources *model.OptionSources) {
				opts.NoRebuild = true
				sources.NoRebuild = model.SourceCLI
			}),
		},
		"force_base_image": {
			boolFlag("--force-base-image", "Bypass devcontainer base image compatibility checks", func(opts *model.Options, sources *model.OptionSources) {
				opts.ForceBaseImage = true
				sources.ForceBaseImage = model.SourceCLI
			}),
		},
		"base_image": {
			valueFlag("--base-image", "Override base image", "--base-image requires a value", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.BaseImage = value
				sources.BaseImage = model.SourceCLI
				return nil
			}),
		},
		"use_remote_user": {
			boolFlag("--use-remote-user", "Use devcontainer remoteUser", func(opts *model.Options, sources *model.OptionSources) {
				opts.UseRemoteUser = true
				sources.UseRemoteUser = model.SourceCLI
			}),
		},
		"slim": {
			boolFlag("--slim", "Tools only, no features", func(opts *model.Options, sources *model.OptionSources) {
				opts.Slim = true
				sources.Slim = model.SourceCLI
			}),
		},
		"image_name": {
			valueFlag("--image-name", "Override image name", "--image-name requires a value", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.ImageName = value
				sources.ImageName = model.SourceCLI
				opts.ImageNameSet = true
				return nil
			}),
		},
		"features": {
			valueFlag("--features", "Enable features (comma-separated), or use default|all|none. In devcontainer mode, features default to none unless set", "--features requires a value", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyFeatures(opts, value); err != nil {
					return err
				}
				sources.Features = model.SourceCLI
				return nil
			}),
		},
		"cache_from": {
			valueFlag("--cache-from", "Reuse build cache from image", "--cache-from requires a value", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyCacheFrom(opts, value); err != nil {
					return err
				}
				sources.CacheFrom = model.SourceCLI
				return nil
			}),
		},
		"build_uid": {
			valueFlag("--build-uid", "UID to bake into the runtime image", "--build-uid requires a numeric UID", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.BuildUID = value
				sources.BuildUID = model.SourceCLI
				return nil
			}),
		},
		"build_gid": {
			valueFlag("--build-gid", "GID to bake into the runtime image", "--build-gid requires a numeric GID", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.BuildGID = value
				sources.BuildGID = model.SourceCLI
				return nil
			}),
		},
		"runtime_uid_remap": {
			boolFlag("--runtime-uid-remap", "Run canonical-UID images after remapping agent to the host UID/GID", func(opts *model.Options, sources *model.OptionSources) {
				opts.RuntimeUIDRemap = true
				sources.RuntimeUIDRemap = model.SourceCLI
			}),
		},
		"buildx_cache_dir": {
			valueFlag("--buildx-cache-dir", "Local buildx cache directory (mode=max export, import when populated)", "--buildx-cache-dir requires a directory path", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.BuildxCacheDir = value
				sources.BuildxCacheDir = model.SourceCLI
				return nil
			}),
		},
		"buildx_cache_from": {
			valueFlag("--buildx-cache-from", "Raw buildx cache import spec (repeatable)", "--buildx-cache-from requires a cache spec", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.BuildxCacheFrom = append(opts.BuildxCacheFrom, value)
				sources.BuildxCacheFrom = model.SourceCLI
				return nil
			}),
		},
		"buildx_cache_to": {
			valueFlag("--buildx-cache-to", "Raw buildx cache export spec (repeatable)", "--buildx-cache-to requires a cache spec", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.BuildxCacheTo = append(opts.BuildxCacheTo, value)
				sources.BuildxCacheTo = model.SourceCLI
				return nil
			}),
		},
		"progress": {
			valueFlag("--progress", "Build output: quiet|compact|verbose", "--progress requires a value (quiet|compact|verbose)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyProgress(opts, value); err != nil {
					return err
				}
				sources.Progress = model.SourceCLI
				return nil
			}),
		},
		"network_log": {
			valueFlag("--network-log", "Network logging mode: coarse|requests", "--network-log requires a value (coarse|requests)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyNetworkLog(opts, value); err != nil {
					return err
				}
				sources.NetworkLog = model.SourceCLI
				return nil
			}),
		},
		"verbose": {
			boolFlag("--verbose", "Enable verbose logging", func(opts *model.Options, sources *model.OptionSources) {
				opts.Verbose = true
				sources.Verbose = model.SourceCLI
			}),
		},
		"ports": {
			valueFlag("-p", "Forward port to container", "-p requires a value", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.Ports = append(opts.Ports, value)
				sources.Ports = model.SourceCLI
				return nil
			}),
		},
		"session_name": {
			valueFlag("--name", "Session name (auto-generated if omitted)", "--name requires a value", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.SessionName = value
				sources.SessionName = model.SourceCLI
				return nil
			}),
		},
		"add_dirs": {
			valueFlag("--add-dir", "Mount additional directory", "--add-dir requires a directory path", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.AddDirs = append(opts.AddDirs, value)
				sources.AddDirs = model.SourceCLI
				return nil
			}),
		},
		"add_readonly_dirs": {
			valueFlag("--add-readonly-dir", "Mount additional directory read-only", "--add-readonly-dir requires a directory path", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.AddReadonlyDirs = append(opts.AddReadonlyDirs, value)
				sources.AddReadonlyDirs = model.SourceCLI
				return nil
			}),
		},
		"project_mount": {
			valueFlag("--project-mount", "Project mount mode: writable|readonly", "--project-mount requires a value (writable|readonly)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyProjectMount(opts, value); err != nil {
					return err
				}
				sources.ProjectMount = model.SourceCLI
				return nil
			}),
		},
		"worktree_metadata": {
			valueFlag("--worktree-metadata", "Linked-worktree git metadata mounts: follow|readonly|none", "--worktree-metadata requires a value (follow|readonly|none)", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyWorktreeMetadata(opts, value); err != nil {
					return err
				}
				sources.WorktreeMetadata = model.SourceCLI
				return nil
			}),
		},
		"allow_domains": {
			valueFlag("--allow-domain", "Add domain to gateway allowlist for this run only (repeatable)", "--allow-domain requires a domain name", func(opts *model.Options, sources *model.OptionSources, value string) error {
				opts.AllowDomains = append(opts.AllowDomains, value)
				sources.AllowDomains = model.SourceCLI
				return nil
			}),
		},
		"playwright_mcp": {
			boolFlag("--playwright-mcp", "Enable Playwright MCP server for browser automation", func(opts *model.Options, sources *model.OptionSources) {
				opts.PlaywrightMCP = true
				sources.PlaywrightMCP = model.SourceCLI
			}),
		},
		"bridge_ports": {
			valueFlag("--bridge-port", "Bridge host port into container (repeatable, comma-separated)", "--bridge-port requires a port number", func(opts *model.Options, sources *model.OptionSources, value string) error {
				if err := applyBridgePort(opts, value); err != nil {
					return err
				}
				sources.BridgePorts = model.SourceCLI
				return nil
			}),
		},
	}
}
